"""Convert annotated LabelMe images to an Ultralytics YOLO dataset."""

from __future__ import annotations

import argparse
import json
import random
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_SOURCE = SCRIPT_DIR / "dataset_raw"
DEFAULT_OUTPUT = SCRIPT_DIR / "dataset"
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
DATASET_MARKER = ".labelme_to_yolo_dataset"


@dataclass(frozen=True)
class Sample:
    json_path: Path
    image_path: Path
    annotation: dict[str, Any]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE, help="LabelMe source folder")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="New YOLO dataset folder")
    parser.add_argument("--val-ratio", type=float, default=0.2, help="Validation fraction (default: 0.2)")
    parser.add_argument("--seed", type=int, default=42, help="Random split seed (default: 42)")
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace an output previously generated by this script",
    )
    return parser.parse_args()


def load_samples(source: Path) -> tuple[list[Sample], list[str]]:
    samples: list[Sample] = []
    labels: set[str] = set()

    for json_path in sorted(source.glob("*.json")):
        try:
            annotation = json.loads(json_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
            print(f"Skip invalid JSON {json_path.name}: {exc}")
            continue

        image_path_value = annotation.get("imagePath")
        candidates: list[Path] = []
        if image_path_value:
            # LabelMe may store either a relative path or an absolute path.
            declared = Path(str(image_path_value))
            candidates.append(declared if declared.is_absolute() else source / declared.name)
        candidates.extend(source / f"{json_path.stem}{ext}" for ext in sorted(IMAGE_EXTENSIONS))
        image_path = next((path for path in candidates if path.is_file()), None)
        if image_path is None:
            print(f"Skip {json_path.name}: matching image not found")
            continue

        shapes = annotation.get("shapes", [])
        valid_labels = {
            str(shape.get("label", "")).strip()
            for shape in shapes
            if str(shape.get("label", "")).strip() and len(shape.get("points", [])) >= 2
        }
        labels.update(valid_labels)
        samples.append(Sample(json_path, image_path.resolve(), annotation))

    return samples, sorted(labels)


def shape_to_yolo(
    shape: dict[str, Any], class_id: int, image_width: int, image_height: int
) -> str | None:
    points = shape.get("points", [])
    try:
        xs = [float(point[0]) for point in points]
        ys = [float(point[1]) for point in points]
    except (TypeError, ValueError, IndexError):
        return None
    if len(xs) < 2:
        return None

    # For detection training, rectangles and polygons are converted to their
    # axis-aligned bounding box. Coordinates are clipped to the image bounds.
    x_min = max(0.0, min(float(image_width), min(xs)))
    x_max = max(0.0, min(float(image_width), max(xs)))
    y_min = max(0.0, min(float(image_height), min(ys)))
    y_max = max(0.0, min(float(image_height), max(ys)))
    if x_max <= x_min or y_max <= y_min:
        return None

    x_center = ((x_min + x_max) / 2.0) / image_width
    y_center = ((y_min + y_max) / 2.0) / image_height
    width = (x_max - x_min) / image_width
    height = (y_max - y_min) / image_height
    return f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}"


def convert_sample(sample: Sample, class_ids: dict[str, int]) -> list[str]:
    try:
        image_width = int(sample.annotation["imageWidth"])
        image_height = int(sample.annotation["imageHeight"])
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"invalid image size in {sample.json_path.name}") from exc
    if image_width <= 0 or image_height <= 0:
        raise ValueError(f"invalid image size in {sample.json_path.name}")

    lines: list[str] = []
    for shape in sample.annotation.get("shapes", []):
        label = str(shape.get("label", "")).strip()
        if label not in class_ids:
            continue
        line = shape_to_yolo(shape, class_ids[label], image_width, image_height)
        if line is not None:
            lines.append(line)
        else:
            print(f"Warning: ignored invalid shape in {sample.json_path.name}")
    return lines


def yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_dataset_yaml(output: Path, classes: list[str]) -> None:
    lines = [
        f"path: {yaml_quote(output.as_posix())}",
        "train: images/train",
        "val: images/val",
        "",
        "names:",
    ]
    lines.extend(f"  {index}: {yaml_quote(name)}" for index, name in enumerate(classes))
    (output / "dataset.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (output / "classes.txt").write_text("\n".join(classes) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    source = args.source.expanduser().resolve()
    output = args.output.expanduser().resolve()
    if not source.is_dir():
        raise SystemExit(f"Source folder does not exist: {source}")
    if output.exists():
        marker = output / DATASET_MARKER
        if not args.overwrite:
            raise SystemExit(
                f"Output already exists: {output}\n"
                "Use --overwrite to regenerate it after adding annotations."
            )
        if not marker.is_file():
            raise SystemExit(
                f"Refusing to overwrite an unrecognized directory: {output}\n"
                f"Safety marker is missing: {marker}"
            )
        shutil.rmtree(output)
    if not 0.0 < args.val_ratio < 1.0:
        raise SystemExit("--val-ratio must be between 0 and 1")

    samples, classes = load_samples(source)
    if len(samples) < 2:
        raise SystemExit("At least two valid LabelMe image/JSON pairs are required")
    if not classes:
        raise SystemExit("No object classes were found in the LabelMe annotations")

    rng = random.Random(args.seed)
    rng.shuffle(samples)
    val_count = max(1, min(len(samples) - 1, round(len(samples) * args.val_ratio)))
    splits = {"val": samples[:val_count], "train": samples[val_count:]}
    class_ids = {name: index for index, name in enumerate(classes)}

    try:
        for split, split_samples in splits.items():
            image_dir = output / "images" / split
            label_dir = output / "labels" / split
            image_dir.mkdir(parents=True, exist_ok=True)
            label_dir.mkdir(parents=True, exist_ok=True)

            for sample in split_samples:
                label_lines = convert_sample(sample, class_ids)
                if not label_lines and sample.annotation.get("shapes"):
                    raise ValueError(f"no valid boxes in {sample.json_path.name}")
                destination = image_dir / sample.image_path.name
                if destination.exists():
                    raise ValueError(f"duplicate image filename: {sample.image_path.name}")
                shutil.copy2(sample.image_path, destination)
                (label_dir / f"{sample.image_path.stem}.txt").write_text(
                    "\n".join(label_lines) + "\n", encoding="utf-8"
                )

        write_dataset_yaml(output, classes)
        (output / DATASET_MARKER).write_text(
            "Generated by labelme_to_yolo.py.\n", encoding="utf-8"
        )
    except Exception:
        # This directory was created by this run, so cleanup cannot affect the
        # original LabelMe data.
        shutil.rmtree(output, ignore_errors=True)
        raise

    print(f"Converted {len(samples)} annotated image(s)")
    print(f"Classes: {', '.join(f'{i}={name}' for i, name in enumerate(classes))}")
    print(f"Train: {len(splits['train'])}, validation: {len(splits['val'])}")
    print(f"Dataset YAML: {output / 'dataset.yaml'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
